import type { PatchNodeDefinition } from './types'

export const nodeRegistry: Record<string, PatchNodeDefinition> = {
  'bang': {
    type: 'bang', label: 'bang', category: 'control',
    inputs: [{ id: 'trigger', label: 'in', direction: 'input', signalType: 'trigger' }],
    outputs: [{ id: 'trigger', label: 'bang', direction: 'output', signalType: 'trigger' }],
    defaultParams: {},
    description: 'Momentary event object for triggering downstream nodes.',
    messages: ['bang'],
    processingRate: 'event',
  },
  'toggle': {
    type: 'toggle', label: 'toggle', category: 'control',
    inputs: [{ id: 'trigger', label: 'bang', direction: 'input', signalType: 'trigger' }],
    outputs: [
      { id: 'value', label: '0/1', direction: 'output', signalType: 'control' },
      { id: 'trigger', label: 'bang', direction: 'output', signalType: 'trigger' },
    ],
    defaultParams: { value: 0 },
    description: 'Boolean control state.',
    messages: ['bang', 'set'],
    processingRate: 'event',
  },
  'number': {
    type: 'number', label: 'number', category: 'control',
    inputs: [{ id: 'value', label: 'in', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'value', label: 'out', direction: 'output', signalType: 'control' }],
    defaultParams: { value: 0.5 },
    description: 'Numeric control box.',
    messages: ['set', 'bang'],
    processingRate: 'control',
  },
  'message': {
    type: 'message', label: 'message', category: 'control',
    inputs: [{ id: 'trigger', label: 'bang', direction: 'input', signalType: 'trigger' }],
    outputs: [{ id: 'value', label: 'out', direction: 'output', signalType: 'control' }],
    defaultParams: { text: '0' },
    description: 'Message box. MVP parses numeric text as a control value.',
    messages: ['bang', 'set'],
    processingRate: 'event',
  },
  'metro': {
    type: 'metro', label: 'metro', category: 'control',
    inputs: [
      { id: 'trigger', label: 'on', direction: 'input', signalType: 'trigger' },
      { id: 'interval', label: 'ms', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'trigger', label: 'bang', direction: 'output', signalType: 'trigger' }],
    defaultParams: { interval: 500, enabled: false },
    description: 'Timed event source. Scheduler execution is stubbed for the browser MVP.',
    messages: ['start', 'stop', 'bang'],
    processingRate: 'event',
  },
  'delay': {
    type: 'delay', label: 'delay', category: 'control',
    inputs: [
      { id: 'trigger', label: 'bang', direction: 'input', signalType: 'trigger' },
      { id: 'time', label: 'ms', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'trigger', label: 'bang', direction: 'output', signalType: 'trigger' }],
    defaultParams: { time: 250 },
    description: 'Delayed event object. Scheduler execution is stubbed for the browser MVP.',
    processingRate: 'event',
  },
  'random': {
    type: 'random', label: 'random', category: 'control',
    inputs: [{ id: 'trigger', label: 'bang', direction: 'input', signalType: 'trigger' }],
    outputs: [{ id: 'value', label: 'out', direction: 'output', signalType: 'control' }],
    defaultParams: { max: 1 },
    description: 'Random control value generator.',
    processingRate: 'event',
  },
  'expr': {
    type: 'expr', label: 'expr', category: 'operator',
    inputs: [
      { id: 'distance', label: 'distance', direction: 'input', signalType: 'control' },
      { id: 'angle', label: 'angle', direction: 'input', signalType: 'control' },
      { id: 'speed', label: 'speed', direction: 'input', signalType: 'control' },
      { id: 'seed', label: 'seed', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'value', label: 'value', direction: 'output', signalType: 'control' }],
    defaultParams: {
      expression: 'sin(angle) * 0.5 + random(seed)',
      distance: 0,
      angle: 0,
      speed: 0,
      seed: 1,
    },
    description: 'Safe formula node. Supports arithmetic, math functions, random(seed), noise, and time variables.',
    processingRate: 'control',
  },
  'counter': {
    type: 'counter', label: 'counter', category: 'control',
    inputs: [{ id: 'trigger', label: 'bang', direction: 'input', signalType: 'trigger' }],
    outputs: [{ id: 'value', label: 'count', direction: 'output', signalType: 'control' }],
    defaultParams: { value: 0, min: 0, max: 16 },
    description: 'Integer counter object.',
    processingRate: 'event',
  },
  'select': {
    type: 'select', label: 'select', category: 'control',
    inputs: [{ id: 'value', label: 'in', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'trigger', label: 'match', direction: 'output', signalType: 'trigger' }],
    defaultParams: { match: 1 },
    description: 'Emits a trigger when incoming value matches.',
    processingRate: 'event',
  },
  'route': {
    type: 'route', label: 'route', category: 'control',
    inputs: [{ id: 'value', label: 'in', direction: 'input', signalType: 'control' }],
    outputs: [
      { id: 'a', label: 'a', direction: 'output', signalType: 'control' },
      { id: 'b', label: 'b', direction: 'output', signalType: 'control' },
    ],
    defaultParams: {},
    description: 'Route-like control splitter placeholder.',
    processingRate: 'event',
  },
  'pack': {
    type: 'pack', label: 'pack', category: 'control',
    inputs: [
      { id: 'a', label: 'a', direction: 'input', signalType: 'control' },
      { id: 'b', label: 'b', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'value', label: 'list', direction: 'output', signalType: 'control' }],
    defaultParams: {},
    description: 'Control list pack placeholder. MVP outputs an averaged scalar.',
    processingRate: 'control',
  },
  'unpack': {
    type: 'unpack', label: 'unpack', category: 'control',
    inputs: [{ id: 'value', label: 'list', direction: 'input', signalType: 'control' }],
    outputs: [
      { id: 'a', label: 'a', direction: 'output', signalType: 'control' },
      { id: 'b', label: 'b', direction: 'output', signalType: 'control' },
    ],
    defaultParams: {},
    description: 'Control list unpack placeholder.',
    processingRate: 'control',
  },
  'send': {
    type: 'send', label: 'send', category: 'control',
    inputs: [{ id: 'value', label: 'in', direction: 'input', signalType: 'control' }],
    outputs: [],
    defaultParams: { name: 'bus' },
    description: 'Named control send placeholder.',
    processingRate: 'event',
  },
  'receive': {
    type: 'receive', label: 'receive', category: 'control',
    inputs: [],
    outputs: [{ id: 'value', label: 'out', direction: 'output', signalType: 'control' }],
    defaultParams: { name: 'bus', value: 0 },
    description: 'Named control receive placeholder.',
    processingRate: 'event',
  },
  'cycle~': {
    type: 'cycle~', label: 'cycle~', category: 'audio',
    inputs: [
      { id: 'frequency', label: 'freq', direction: 'input', signalType: 'control' },
      { id: 'detune', label: 'detune', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { frequency: 440, waveform: 'sine' },
    description: 'Signal-rate sine oscillator.',
    processingRate: 'signal',
  },
  'phasor~': {
    type: 'phasor~', label: 'phasor~', category: 'audio',
    inputs: [{ id: 'frequency', label: 'freq', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { frequency: 1, waveform: 'sawtooth' },
    description: 'Signal-rate ramp oscillator approximation.',
    processingRate: 'signal',
  },
  'noise~': {
    type: 'noise~', label: 'noise~', category: 'audio',
    inputs: [],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { type: 'white' },
    description: 'Signal-rate noise source.',
    processingRate: 'signal',
  },
  'sig~': {
    type: 'sig~', label: 'sig~', category: 'audio',
    inputs: [{ id: 'value', label: 'value', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { value: 0 },
    description: 'Control to constant signal placeholder.',
    processingRate: 'signal',
  },
  'line~': {
    type: 'line~', label: 'line~', category: 'audio',
    inputs: [{ id: 'value', label: 'target', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { value: 0, time: 0.05 },
    description: 'Ramped signal placeholder.',
    processingRate: 'signal',
  },
  'gain~': {
    type: 'gain~', label: 'gain~', category: 'audio',
    inputs: [
      { id: 'audio', label: 'signal', direction: 'input', signalType: 'audio' },
      { id: 'gain', label: 'gain', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { gain: 0.7 },
    description: 'Signal gain processor.',
    processingRate: 'signal',
  },
  'filter~': {
    type: 'filter~', label: 'filter~', category: 'audio',
    inputs: [
      { id: 'audio', label: 'signal', direction: 'input', signalType: 'audio' },
      { id: 'frequency', label: 'cutoff', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { frequency: 1200, type: 'lowpass' },
    description: 'Signal filter processor.',
    processingRate: 'signal',
  },
  'delay~': {
    type: 'delay~', label: 'delay~', category: 'audio',
    inputs: [
      { id: 'audio', label: 'signal', direction: 'input', signalType: 'audio' },
      { id: 'time', label: 'time', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { time: 0.25, feedback: 0.2 },
    description: 'Signal delay processor.',
    processingRate: 'signal',
  },
  'mix~': {
    type: 'mix~', label: 'mix~', category: 'audio',
    inputs: [
      { id: 'audio', label: 'a', direction: 'input', signalType: 'audio' },
      { id: 'audioB', label: 'b', direction: 'input', signalType: 'audio' },
    ],
    outputs: [{ id: 'audio', label: 'sum', direction: 'output', signalType: 'audio' }],
    defaultParams: { gain: 1 },
    description: 'Signal summing node.',
    processingRate: 'signal',
  },
  'adc~': {
    type: 'adc~', label: 'adc~', category: 'audio',
    inputs: [],
    outputs: [{ id: 'audio', label: 'input', direction: 'output', signalType: 'audio' }],
    defaultParams: {},
    description: 'Audio input placeholder.',
    processingRate: 'signal',
  },
  'dac~': {
    type: 'dac~', label: 'dac~', category: 'output',
    inputs: [{ id: 'audio', label: 'signal', direction: 'input', signalType: 'audio' }],
    outputs: [],
    defaultParams: { volume: 0.8 },
    description: 'Audio output destination.',
    processingRate: 'signal',
  },
  'sampler~': {
    type: 'sampler~', label: 'sampler~', category: 'audio',
    inputs: [
      { id: 'trigger', label: 'trigger', direction: 'input', signalType: 'trigger' },
      { id: 'sample', label: 'sample', direction: 'input', signalType: 'sample' },
    ],
    outputs: [{ id: 'audio', label: 'signal', direction: 'output', signalType: 'audio' }],
    defaultParams: { sampleId: null, playbackRate: 1.0, gain: 0.8 },
    description: 'Triggered sampler with fallback synthesized click.',
    processingRate: 'signal',
  },
  'curve-reader': {
    type: 'curve-reader', label: 'curve-reader', category: 'geometry',
    inputs: [],
    outputs: [{ id: 'geometryList', label: 'curves', direction: 'output', signalType: 'geometryList' }],
    defaultParams: {},
    description: 'Reads all visible curve geometry from the canvas.',
    processingRate: 'geometry',
  },
  'shape.area': {
    type: 'shape.area', label: 'shape.area', category: 'geometry',
    inputs: [{ id: 'geometry', label: 'shape', direction: 'input', signalType: 'geometry' }],
    outputs: [{ id: 'value', label: 'area', direction: 'output', signalType: 'control' }],
    defaultParams: {},
    description: 'Geometry feature extractor: area.',
    processingRate: 'geometry',
  },
  'path.length': {
    type: 'path.length', label: 'path.length', category: 'geometry',
    inputs: [{ id: 'geometry', label: 'curve', direction: 'input', signalType: 'geometry' }],
    outputs: [{ id: 'value', label: 'length', direction: 'output', signalType: 'control' }],
    defaultParams: {},
    description: 'Geometry feature extractor: curve length.',
    processingRate: 'geometry',
  },
  'area-to-pitch': {
    type: 'area-to-pitch', label: 'area-to-pitch', category: 'operator',
    inputs: [{ id: 'value', label: 'area', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'value', label: 'pitch', direction: 'output', signalType: 'control' }],
    defaultParams: { inMin: 0, inMax: 10000, outMin: 100, outMax: 1000 },
    description: 'Maps geometry area into pitch control.',
    processingRate: 'control',
  },
  'geometry-lfo': {
    type: 'geometry-lfo', label: 'geometry-lfo', category: 'geometry',
    inputs: [{ id: 'geometry', label: 'shape', direction: 'input', signalType: 'geometry' }],
    outputs: [{ id: 'value', label: 'mod', direction: 'output', signalType: 'control' }],
    defaultParams: { rate: 1, amount: 1 },
    description: 'Geometry-derived modulation placeholder.',
    processingRate: 'control',
  },
  'point-cloud': {
    type: 'point-cloud', label: 'point-cloud', category: 'geometry',
    inputs: [{ id: 'geometryList', label: 'source', direction: 'input', signalType: 'geometryList' }],
    outputs: [{ id: 'geometryList', label: 'points', direction: 'output', signalType: 'geometryList' }],
    defaultParams: { count: 32 },
    description: 'Point-cloud geometry placeholder for later shape sampling.',
    processingRate: 'geometry',
  },
  'length-to-envelope': {
    type: 'length-to-envelope', label: 'length-to-envelope', category: 'operator',
    inputs: [{ id: 'value', label: 'length', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'value', label: 'env', direction: 'output', signalType: 'control' }],
    defaultParams: { inMin: 0, inMax: 1000, outMin: 0.01, outMax: 1 },
    description: 'Maps curve length into envelope time.',
    processingRate: 'control',
  },
  'density-to-noise': {
    type: 'density-to-noise', label: 'density-to-noise', category: 'operator',
    inputs: [{ id: 'value', label: 'density', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'value', label: 'noise', direction: 'output', signalType: 'control' }],
    defaultParams: { amount: 1 },
    description: 'Maps point density into noise amount.',
    processingRate: 'control',
  },
  'gesture-recorder': {
    type: 'gesture-recorder', label: 'gesture-recorder', category: 'geometry',
    inputs: [{ id: 'geometry', label: 'gesture', direction: 'input', signalType: 'geometry' }],
    outputs: [{ id: 'geometry', label: 'path', direction: 'output', signalType: 'geometry' }],
    defaultParams: { recording: false },
    description: 'Gesture capture placeholder.',
    processingRate: 'geometry',
  },
  'audio.oscillator': {
    type: 'audio.oscillator', label: 'Osc', category: 'audio',
    inputs: [
      { id: 'frequency', label: 'freq', direction: 'input', signalType: 'control' },
      { id: 'detune',    label: 'det',  direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'audio', label: 'out', direction: 'output', signalType: 'audio' }],
    defaultParams: { waveform: 'sine', frequency: 440, gain: 0.5 },
  },
  'audio.gain': {
    type: 'audio.gain', label: 'Gain', category: 'audio',
    inputs: [
      { id: 'audio', label: 'in',   direction: 'input', signalType: 'audio' },
      { id: 'gain',  label: 'gain', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'audio', label: 'out', direction: 'output', signalType: 'audio' }],
    defaultParams: { gain: 0.7 },
  },
  'audio.output': {
    type: 'audio.output', label: 'Out', category: 'output',
    inputs: [{ id: 'audio', label: 'in', direction: 'input', signalType: 'audio' }],
    outputs: [],
    defaultParams: { volume: 0.8 },
  },
  'audio.sampler': {
    type: 'audio.sampler', label: 'Sampler', category: 'audio',
    inputs: [
      { id: 'trigger', label: 'trigger', direction: 'input', signalType: 'trigger' },
      { id: 'sample',  label: 'sample',  direction: 'input', signalType: 'sample' },
    ],
    outputs: [{ id: 'audio', label: 'audio', direction: 'output', signalType: 'audio' }],
    defaultParams: { sampleId: null, playbackRate: 1.0, gain: 0.8 },
  },
  'control.lfo': {
    type: 'control.lfo', label: 'LFO', category: 'control',
    inputs: [{ id: 'rate', label: 'rate', direction: 'input', signalType: 'control' }],
    outputs: [{ id: 'value', label: 'val', direction: 'output', signalType: 'control' }],
    defaultParams: { waveform: 'sine', rate: 1.0, min: 0, max: 1 },
  },
  'control.number': {
    type: 'control.number', label: 'Number', category: 'control',
    inputs: [],
    outputs: [{ id: 'value', label: 'val', direction: 'output', signalType: 'control' }],
    defaultParams: { value: 0.5 },
  },
  'control.trigger': {
    type: 'control.trigger', label: 'Trigger', category: 'control',
    inputs: [],
    outputs: [{ id: 'trigger', label: 'trig', direction: 'output', signalType: 'trigger' }],
    defaultParams: { mode: 'momentary' },
  },
  'geometry.referenceCircle': {
    type: 'geometry.referenceCircle', label: 'Ref Circle', category: 'geometry',
    inputs: [{ id: 'circle', label: 'circ', direction: 'input', signalType: 'geometry' }],
    outputs: [{ id: 'geometry', label: 'geom', direction: 'output', signalType: 'geometry' }],
    defaultParams: { geometryId: '' },
  },
  'geometry.referencePoint': {
    type: 'geometry.referencePoint', label: 'Ref Point', category: 'geometry',
    inputs: [{ id: 'point', label: 'pt', direction: 'input', signalType: 'geometry' }],
    outputs: [{ id: 'geometry', label: 'geom', direction: 'output', signalType: 'geometry' }],
    defaultParams: { geometryId: '' },
  },
  'geometry.referenceCurve': {
    type: 'geometry.referenceCurve', label: 'Ref Curve', category: 'geometry',
    inputs: [],
    outputs: [{ id: 'geometry', label: 'geom', direction: 'output', signalType: 'geometry' }],
    defaultParams: { geometryId: '' },
  },
  'geometry.referenceAllCurves': {
    type: 'geometry.referenceAllCurves', label: 'Ref All Curves', category: 'geometry',
    inputs: [],
    outputs: [{ id: 'geometryList', label: 'curves', direction: 'output', signalType: 'geometryList' }],
    defaultParams: {},
  },
  'geometry.circleParams': {
    type: 'geometry.circleParams', label: 'Circle Params', category: 'operator',
    inputs: [{ id: 'geometry', label: 'geom', direction: 'input', signalType: 'geometry' }],
    outputs: [
      { id: 'cx',           label: 'cx',   direction: 'output', signalType: 'control' },
      { id: 'cy',           label: 'cy',   direction: 'output', signalType: 'control' },
      { id: 'radius',       label: 'r',    direction: 'output', signalType: 'control' },
      { id: 'area',         label: 'area', direction: 'output', signalType: 'control' },
      { id: 'circumference',label: 'circ', direction: 'output', signalType: 'control' },
      { id: 'orbitDistance',label: 'dist', direction: 'output', signalType: 'control' },
      { id: 'orbitTime',    label: 'time', direction: 'output', signalType: 'control' },
    ],
    defaultParams: {},
  },
  'geometry.pointOnCurve': {
    type: 'geometry.pointOnCurve', label: 'Point On Curve', category: 'operator',
    inputs: [
      { id: 'curve', label: 'crv', direction: 'input', signalType: 'geometry' },
      { id: 'speed', label: 'spd', direction: 'input', signalType: 'control' },
    ],
    outputs: [
      { id: 'geometry', label: 'pt', direction: 'output', signalType: 'geometry' },
      { id: 'x',        label: 'x',  direction: 'output', signalType: 'control' },
      { id: 'y',        label: 'y',  direction: 'output', signalType: 'control' },
    ],
    defaultParams: { speed: 80, offset: 0 },
  },
  'geometry.circleFromPoint': {
    type: 'geometry.circleFromPoint', label: 'Circle From Point', category: 'operator',
    inputs: [
      { id: 'point',  label: 'pt', direction: 'input', signalType: 'geometry' },
      { id: 'radius', label: 'r',  direction: 'input', signalType: 'control' },
    ],
    outputs: [
      { id: 'geometry',     label: 'geom', direction: 'output', signalType: 'geometry' },
      { id: 'radius',       label: 'r',    direction: 'output', signalType: 'control' },
      { id: 'area',         label: 'area', direction: 'output', signalType: 'control' },
      { id: 'circumference',label: 'circ', direction: 'output', signalType: 'control' },
    ],
    defaultParams: { radius: 60 },
  },
  'geometry.circleOrbit': {
    type: 'geometry.circleOrbit', label: 'Circle Orbit', category: 'operator',
    inputs: [
      { id: 'circle', label: 'circ', direction: 'input', signalType: 'geometry' },
      { id: 'orbitDistance', label: 'dist', direction: 'input', signalType: 'control' },
      { id: 'orbitTime',     label: 'time', direction: 'input', signalType: 'control' },
    ],
    outputs: [{ id: 'geometry', label: 'geom', direction: 'output', signalType: 'geometry' }],
    defaultParams: { orbitDistance: 628, orbitTime: 2 },
  },
  'geometry.geoTrigger': {
    type: 'geometry.geoTrigger', label: 'Geo Trigger', category: 'operator',
    inputs: [
      { id: 'a', label: 'geo a', direction: 'input', signalType: 'geometry' },
      { id: 'b', label: 'geo b', direction: 'input', signalType: 'geometry' },
      { id: 'c', label: 'geo c', direction: 'input', signalType: 'geometry' },
      { id: 'd', label: 'geo d', direction: 'input', signalType: 'geometry' },
      { id: 'geometryList', label: 'list', direction: 'input', signalType: 'geometryList' },
    ],
    outputs: [{ id: 'trigger', label: 'trigger', direction: 'output', signalType: 'trigger' }],
    defaultParams: {},
  },
  'geometry.drawCircle': {
    type: 'geometry.drawCircle', label: 'Draw Circle', category: 'geometry',
    inputs: [
      { id: 'point',  label: 'pt', direction: 'input', signalType: 'geometry' },
      { id: 'cx',     label: 'cx', direction: 'input', signalType: 'control' },
      { id: 'cy',     label: 'cy', direction: 'input', signalType: 'control' },
      { id: 'radius', label: 'r',  direction: 'input', signalType: 'control' },
    ],
    outputs: [
      { id: 'geometry',     label: 'geom', direction: 'output', signalType: 'geometry' },
      { id: 'radius',       label: 'r',    direction: 'output', signalType: 'control' },
      { id: 'area',         label: 'area', direction: 'output', signalType: 'control' },
      { id: 'circumference',label: 'circ', direction: 'output', signalType: 'control' },
    ],
    defaultParams: { cx: 300, cy: 200, r: 100 },
  },
  'geometry.drawPoint': {
    type: 'geometry.drawPoint', label: 'Draw Point', category: 'geometry',
    inputs: [
      { id: 'x', label: 'x', direction: 'input', signalType: 'control' },
      { id: 'y', label: 'y', direction: 'input', signalType: 'control' },
    ],
    outputs: [
      { id: 'geometry', label: 'geom', direction: 'output', signalType: 'geometry' },
      { id: 'x',        label: 'x',    direction: 'output', signalType: 'control' },
      { id: 'y',        label: 'y',    direction: 'output', signalType: 'control' },
    ],
    defaultParams: { x: 300, y: 200 },
  },
  'geometry.drawPath': {
    type: 'geometry.drawPath', label: 'Draw Path', category: 'geometry',
    inputs: [],
    outputs: [
      { id: 'geometry', label: 'geom', direction: 'output', signalType: 'geometry' },
      { id: 'length',   label: 'len',  direction: 'output', signalType: 'control' },
    ],
    defaultParams: { svgPath: 'M 100 100 C 160 40, 240 160, 300 100' },
  },
  'display.geometry': {
    type: 'display.geometry', label: 'Display Geometry', category: 'display',
    inputs: [
      { id: 'geometry', label: 'geom', direction: 'input', signalType: 'geometry' },
      { id: 'geometryList', label: 'list', direction: 'input', signalType: 'geometryList' },
    ],
    outputs: [],
    defaultParams: {
      stroke: '#2563eb',
      fill: 'none',
      strokeWidth: 2,
      opacity: 1,
    },
  },
}

export const nodeLibraryOrder: Array<{ category: string; types: string[] }> = [
  {
    category: 'Message / Control',
    types: ['bang', 'toggle', 'number', 'message', 'metro', 'delay', 'random', 'expr', 'counter', 'select', 'route', 'pack', 'unpack', 'send', 'receive'],
  },
  {
    category: 'Signal',
    types: ['cycle~', 'phasor~', 'noise~', 'sig~', 'line~', 'gain~', 'filter~', 'delay~', 'mix~', 'adc~', 'dac~', 'sampler~'],
  },
  {
    category: 'Geometry',
    types: [
      'curve-reader',
      'shape.area',
      'path.length',
      'point-cloud',
      'gesture-recorder',
      'geometry-lfo',
      'geometry.referenceCircle',
      'geometry.referencePoint',
      'geometry.referenceCurve',
      'geometry.referenceAllCurves',
      'geometry.drawCircle',
      'geometry.drawPoint',
      'geometry.drawPath',
    ],
  },
  {
    category: 'Mapping / Operators',
    types: [
      'area-to-pitch',
      'length-to-envelope',
      'density-to-noise',
      'geometry.circleParams',
      'geometry.pointOnCurve',
      'geometry.circleFromPoint',
      'geometry.circleOrbit',
      'geometry.geoTrigger',
    ],
  },
  { category: 'Display', types: ['display.geometry'] },
]
